fixup! (CR): dt: Add Moto dtb and dtbo base for arcf
rebase 8635 r1.0.r1_00023.0 build error:
[529 / 602] Generating build config @//msm-kernel:pineapple_consolidate_build_config; 0s linux-sandbox ... (4 actions, 3 running)
ERROR: /home/zhangxu21/Work/8650-rebase/8635-rebase-00023/rebase-base-qcom023/vendor_u/kernel_platform/msm-kernel/BUILD.bazel:346:21: Executing genrule //msm-kernel:pineapple_consolidate_dpm_image failed: missing input file '//msm-kernel:pineapple_consolidate/pineapple-dpm-overlay.dtbo'
ERROR: /home/zhangxu21/Work/8650-rebase/8635-rebase-00023/rebase-base-qcom023/vendor_u/kernel_platform/msm-kernel/BUILD.bazel:346:21: Executing genrule //msm-kernel:pineapple_consolidate_dpm_image failed: 1 input file(s) do not exist
Use --verbose_failures to see the command lines of failed build steps.
Change-Id: I0681f08f7ae1333ab660fca1c8a0c6a8e70c9da1
Reviewed-on: https://gerrit.mot.com/2788365
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Submit-Approved: Jira Key
Tested-by: Jira Key
Reviewed-by: Xu Zhang <zhangxu21@lenovo.com>
(cherry picked from commit d5c3fc48560cc534256b27f578a502967fbe7252)
Reviewed-on: https://gerrit.mot.com/2791430
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Xu Zhang <zhangxu21@lenovo.com>