Revert "ARM: dts: msm: Remove xo-therm critical trip for CAPE"
This reverts commit 80cb6b57af4f713a712decc3b6108fa83c1370a9.
Until Moto updates our own code:
+++
ERROR: ufdt_overlay_do_fixups():Couldn't find 'xo_config2' symbol in main dtb
ERROR: ufdt_overlay_apply():failed to perform fixups in overlay
  DTC     arch/arm64/boot/dts/qcom/sc7180-trogdor-lazor-r0.dtb
ERROR: ufdt_overlay_do_fixups():Couldn't find 'xo_config2' symbol in main dtb
ERROR: ufdt_overlay_apply():failed to perform fixups in overlay
ERROR: ufdt_overlay_do_fixups():Couldn't find 'xo_config2' symbol in main dtb
ERROR: ufdt_overlay_apply():failed to perform fixups in overlay
  DTC     arch/arm64/boot/dts/allwinner/sun50i-h5-nanopi-neo2.dtb
+++

Signed-off-by: Yinjun Chen <a7301c@motorola.com>