Revert "ARM: dts: qcom: Update critical trip type to passive for taro"
This reverts commit 1fdd771ca8517f8f0355e05183ad82ee180df39f.
+++++For the following build error:
ERROR: ufdt_overlay_do_fixups():Couldn't find 'xo_config2' symbol in main dtb
ERROR: ufdt_overlay_apply():failed to perform fixups in overlay
ERROR: ufdt_overlay_do_fixups():Couldn't find 'xo_config2' symbol in main dtb
ERROR: ufdt_overlay_apply():failed to perform fixups in overlay
Segmentation fault (core dumped)
++++++

Change-Id: I97ba9d4e63bc0ff8be3a8dd8417a215cdac72d26