fix makalu init build error
ERROR: /home/xiest1/makalu/mw-qc/kernel_platform/soc-repo/BUILD.bazel:309:13: Building boot images //soc-repo:canoe_consolidate_images_boot_images failed: (Exit 1): bash failed: error executing BootImages command (from target //soc-repo:canoe_consolidate_images_boot_images) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
WARNING: VENDOR_BOOTCONFIG is deprecated. Use vendor_boot_image.vendor_bootconfig instead.
ERROR: Unable to find dtb.img in any of the following directories:
  /home/xiest1/makalu/mw-qc/bazel-cache/88ef7aad5d214f3838f8f90874914756/sandbox/linux-sandbox/2322/execroot/_main/out/android16-6.12/dist
init_boot image created at /home/xiest1/makalu/mw-qc/bazel-cache/88ef7aad5d214f3838f8f90874914756/sandbox/linux-sandbox/2322/execroot/_main/out/android16-6.12/dist/init_boot.img
[6,543 / 6,543] no actions running
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/xiest1/makalu/mw-qc/kernel_platform/soc-repo/BUILD.bazel:309:13 Middleman _middlemen/soc-repo_Scanoe_Uconsolidate_Udist-runfiles failed: (Exit 1): bash failed: error executing BootImages command (from target //soc-repo:canoe_consolidate_images_boot_images) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 587.748s, Critical Path: 566.02s
INFO: 6055 processes: 489 action cache hit, 3732 internal, 2323 linux-sandbox.

Change-Id: Icbd90dad9e5101fab3b09ac040ae1c631df0408f
(cherry picked from commit fbb046e684ab9130de2f0f7b08a5c6d2a2abcb5c)
Reviewed-on: https://gerrit.mot.com/3806013
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Tested-by: Jira Key
Submit-Approved: Jira Key